#!/bin/ruby

=begin
puts `pdflatex thesis.tex`
puts `bibtex thesis.aux`
puts `pdflatex thesis.tex`
puts `pdflatex thesis.tex`
=end

puts `TEXINPUTS=.//:$(TEXINPUTS) pdflatex thesis.tex`
puts `TEXINPUTS=.//:$(TEXINPUTS) bibtex thesis.aux`
puts `TEXINPUTS=.//:$(TEXINPUTS) pdflatex thesis.tex`
puts `TEXINPUTS=.//:$(TEXINPUTS) pdflatex thesis.tex`
