#!/bin/ruby

puts `pdflatex thesis`
puts `bibtex thesis`
puts `pdflatex thesis`
puts `pdflatex thesis`

=begin
puts `TEXINPUTS=.//:$(TEXINPUTS) pdflatex thesis.tex`
puts `TEXINPUTS=.//:$(TEXINPUTS) bibtex thesis.aux`
puts `TEXINPUTS=.//:$(TEXINPUTS) pdflatex thesis.tex`
puts `TEXINPUTS=.//:$(TEXINPUTS) pdflatex thesis.tex`
=end
